
const Array = [
    {
      id: 0,
      name: 'User 1',
      photo: 'https://i.pinimg.com/736x/8b/16/7a/8b167af653c2399dd93b952a48740620.jpg',
      Bio: 'Software Developer, India',
      description: 'Just one small positive thought in the morning can change your whole day',
      image: 'https://plus.unsplash.com/premium_photo-1664474619075-644dd191935f?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 1,
      name: 'User 2',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCwXFbpWQJzEvfTNGePdj95M250jlNpMFIZ_hlTsd6Go6ZsEX9asR-Z0H8Y4PZwcV0bAY&usqp=CAU',
      Bio: 'Software Engineer, India',
      description: '“Try not to become a man of success, but rather try to become a man of value.”',
      image: 'https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 2,
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-I8sc0-8ejEAggzXAm9mxB0TmKWm24XJUQaWz-WyBgtiungnZDwvC1LaBX5CUrvLmcT4&usqp=CAU',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 3,
      name: 'User 4',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSADCNb2Pjkg0GPJOwfI9Ktfp4EtO6VNMsw6nbkDKEDp2X0pu4AhDVDQiPQBJ-K_Y2gdys&usqp=CAU',
      Bio: 'Python Developer, India',
      description: 'Either you run the day or the day runs you, it means you can manage, control the time what you want',
      image: 'https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 4,
      name: 'User 5',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAXkm9cY-Ipyw3K7evHgNYtEyyE8BR-UnS_038_nPtW_tMa2vVNLCvUghurggQQ-Vzq0c&usqp=CAU',
      Bio: 'React Developer, India',
      description: 'Perseverance is not a long race; it is many short races one after the other.',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6D6L-tO--2vsGd6XlgXwFpa3LWthJwXFmR8f7vVz7ZvBzhLSsk2Lqg1DYbuvCbBS6PBM&usqp=CAU',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 5,
      name: 'User 6',
      photo: 'https://i.pinimg.com/736x/8b/16/7a/8b167af653c2399dd93b952a48740620.jpg',
      Bio: 'Software Developer, India',
      description: 'Action is the foundational key to all success',
      image: 'https://rszr.getimg.ai/resize?url=https%3A%2F%2Fimg1.getimg.ai%2Fgenerated%2F3bcfb5df-0400-40c2-b31d-3e8b08e29ade%2Fimg-7rFkxY2FNxXdYTStZ33D0.jpeg&type=webp&width=3840&speed=5',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 6,
      name: 'User 7',
      photo: 'https://png.pngtree.com/png-clipart/20231019/original/pngtree-user-profile-avatar-png-image_13369989.png',
      Bio: 'ML Engineer, India',
      description: 'Just made something pretty cool Every step, every detail, every prompt wes all in this thread',
      image: 'https://gratisography.com/wp-content/uploads/2024/10/gratisography-happy-cone-800x525.jpg',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 7,
      name: 'User 8',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScdEP0XYKKbu-mQ7XY8mzYlbZqjAMXr_nDqHInVXmNm_dNsld1aLON8Ud4KNx6g8u2JuA&usqp=CAU',
      Bio: 'Java Developer, India',
      description: '“It is never too late to be what you might have been.”',
      image: 'https://pixlr.com/images/generator/image-editor.webp',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 8,
      name: 'User 9',
      photo: 'https://png.pngtree.com/png-vector/20221203/ourmid/pngtree-cartoon-style-female-user-profile-icon-vector-illustraton-png-image_6489286.png',
      Bio: 'Software Developer, India',
      description: '“Opportunities don’t happen, you create them.”',
      image: 'https://www.akamai.com/site/im-demo/perceptual-standard.jpg?imbypass=true',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 9,
      name: 'User 10',
      photo: 'https://i.pinimg.com/736x/e9/36/ab/e936ab240156c33be7974c2c36188bdf.jpg',
      Bio: 'Animated Cartoon, Japan',
      description: '“Opportunities don’t happen, you create them.”',
      image: 'https://miro.medium.com/v2/resize:fit:736/1*w4MhPHkH-c_EAnsRXeB68Q.jpeg',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 10,
      name: 'User 11',
      photo: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Doraemon_character.png',
      Bio: 'Animated Cartoon, Japan',
      description: '“Opportunities don’t happen, you create them.”',
      image: 'https://rukminim2.flixcart.com/image/850/1000/kkwwu4w0/poster/3/n/y/extra-large-doraemon-cartoon-waterproof-vinyl-sticker-poster-original-imagy5evpj9tbsg4.jpeg?q=90&crop=false',
      tags: '#welcome #good',
      comments: [],
    },
];
    
    export default Array