const UserContent = {
  Entertainment: [
    {
      id: 1,
      title: "Movie News",
      description: "Latest blockbuster updates",
      name: 'User 1',
      photo: 'https://i.pinimg.com/736x/8b/16/7a/8b167af653c2399dd93b952a48740620.jpg',
      Bio: 'Software Developer, India',
      description: 'Latest blockbuster updates',
      image: 'https://plus.unsplash.com/premium_photo-1664474619075-644dd191935f?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
      tags: '#welcome #good',
      comments: [],
    },
    {
      id: 2,
      title: "Celebrity Gossip",
      description: "Trending celebrity stories",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-I8sc0-8ejEAggzXAm9mxB0TmKWm24XJUQaWz-WyBgtiungnZDwvC1LaBX5CUrvLmcT4&usqp=CAU',
      tags: '#welcome #good',
    },
    {
      id: 3,
      title: "Celebrity Gossip",
      description: "Trending celebrity stories",
      name: 'User 4',
      photo: 'https://st3.depositphotos.com/15648834/17930/v/450/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg',
      Bio: 'UI UX, India',
      description: 'We aren t in an information age, we are in an entertainment age. ...',
      image: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg?cs=srgb&dl=pexels-annamw-1047442.jpg&fm=jpg',
      tags: '#welcome #good',
    },
    {
      id: 4,
      title: "Celebrity Gossip",
      description: "Trending celebrity stories",
      name: 'User 5',
      photo: 'https://static.vecteezy.com/system/resources/thumbnails/004/607/791/small_2x/man-face-emotive-icon-smiling-male-character-in-blue-shirt-flat-illustration-isolated-on-white-happy-human-psychological-portrait-positive-emotions-user-avatar-for-app-web-design-vector.jpg',
      Bio: 'UI UX, India',
      description: 'All our dreams can come true, if we have the courage to pursue them',
      image: 'https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/image/rDtN98Qoishumwih/illustration-of-film-stripe-with-entertainment-objects-on-musical-notes-background_thumb.jpg',
      tags: '#welcome #good',
    },
    {
      id: 5,
      title: "Celebrity Gossip",
      description: "Trending celebrity stories",
      name: 'User 6',
      photo: 'https://www.shutterstock.com/image-illustration/2d-illustration-flat-design-profile-260nw-1874880814.jpg',
      Bio: 'UI UX, India',
      description: 'Some men see things as they are and say why',
      image: 'https://nationaleconomy.com/wp-content/uploads/2022/09/istock_85340257_small.jpg',
      tags: '#welcome #good',
    },
    {
      id: 6,
      title: "Celebrity Gossip",
      description: "Trending celebrity stories",
      name: 'User 7',
      photo: 'https://www.shutterstock.com/image-vector/illustration-vector-graphic-male-avatar-260nw-1926519032.jpg',
      Bio: 'UI UX, India',
      description: 'The future belongs to those who believe in the beauty of their dreams',
      image: 'https://blog.ipleaders.in/wp-content/uploads/2021/06/featured.jpg',
      tags: '#welcome #good',
    },
  ],
  Educational: [
    {
      id: 1,
      title: "Math Tips",
      description: "Learn algebra quickly",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://plus.unsplash.com/premium_photo-1682125773446-259ce64f9dd7?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWR1Y2F0aW9ufGVufDB8fDB8fHww',
      tags: '#welcome #good',
    },
    {
      id: 2,
      title: "Math Tips",
      description: "Learn algebra quickly",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://www.shutterstock.com/shutterstock/photos/767491552/display_1500/stock-vector-education-tree-of-knowledge-and-open-book-effective-modern-education-template-design-back-to-767491552.jpg',
      tags: '#welcome #good'
    },
  ],
  Fitness: [
    {
      id: 1,
      title: "Workout Routines",
      description: "Full-body exercises",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://gosharpener.com/content/uploads/photos/2024/07/sngine_129aed8e66617095e117e3f22e812d0d.png',
      tags: '#welcome #good'
    },
    {
      id: 2, title: "Healthy Diets", description: "Nutritious meal plans",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://churchviewmedicalpractice.com/images/health_images/physical-activity.jpg',
      tags: '#welcome #good'
    },
  ],
  Devotional: [
    {
      id: 1, title: "Morning Prayer", description: "Start your day with devotion",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://www.shutterstock.com/image-illustration/saraswati-devi-goddess-happy-vasant-600nw-1913438200.jpg',
      tags: '#welcome #good'
    },
    {
      id: 2, title: "Spiritual Quotes", description: "Daily spiritual inspiration",
      name: 'User 3',
      photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBJT5wHCiGz1_ahHSkMCToJutWRc7_GtpEklerkC0wtu0zj9j0mRsCuUVCWRx4gtCQkc&usqp=CAU',
      Bio: 'UI UX, India',
      description: 'Success consists of going from failure to failure without loss of enthusiasm',
      image: 'https://i.pinimg.com/736x/7f/5d/fa/7f5dfaa1723c250053b4db5f97dbf1d2.jpg',
      tags: '#welcome #good'
    },
  ],
  All: [], // 'All' mode dynamically includes all categories
};

export default UserContent;